export const styles: string[] = [
  "Modern",
  "Contemporary",
  "Minimalist",
  "Scandinavian",
  "Industrial",
  "Mid-Century Modern",
  "Art Deco",
  "Traditional",
  "Transitional",
  "Rustic",
  "Farmhouse",
  "Country",
  "Coastal",
  "Mediterranean",
  "Bohemian",
  "Eclectic",
  "Vintage",
  "Retro",
  "Victorian",
  "Georgian",
  "Colonial",
  "Neoclassical",
  "Gothic",
  "Baroque",
  "Rococo",
  "Asian",
  "Japanese",
  "Zen",
  "Moroccan",
  "Tropical",
  "Hollywood Regency",
  "Shabby Chic",
  "French Country",
  "Tuscan",
  "Southwestern",
  "Art Nouveau",
  "Bauhaus",
  "Brutalist",
  "Futuristic",
  "Steampunk",
  "Wabi-Sabi",
  "Memphis",
  "Postmodern",
  "Urban",
  "Loft",
  "Nautical",
  "Lodge",
  "High-Tech",
  "Maximalist",
];

export const roomTypes = [
  "Living Room",
  "Dining Room",
  "Kitchen",
  "Bedroom",
  "Master Bedroom",
  "Bathroom",
  "Ensuite Bathroom",
  "Powder Room",
  "Home Office",
  "Study",
  "Library",
  "Family Room",
  "Playroom",
  "Nursery",
  "Guest Room",
  "Mudroom",
  "Laundry Room",
  "Pantry",
  "Walk-in Closet",
  "Attic",
  "Basement",
  "Garage",
  "Sunroom",
  "Conservatory",
  "Conference Room",
  "Meeting Room",
  "Open Office",
  "Private Office",
  "Reception Area",
  "Waiting Room",
  "Break Room",
  "Cafeteria",
  "Auditorium",
  "Classroom",
  "Laboratory",
  "Workshop",
  "Hotel Room",
  "Suite",
  "Lobby",
  "Restaurant Dining Area",
  "Bar",
  "Lounge",
  "Home Theater",
  "Game Room",
  "Gym",
  "Wine Cellar",
  "Sauna",
  "Meditation Room",
  "Art Studio",
  "Music Room",
  "Greenhouse",
];

export const colorSchemes = [
  {
    name: "Crisp Winter",
    colors: ["#304050", "#B0C0D0", "#E0E0E0"],
  },
  {
    name: "Rustic Farmhouse",
    colors: ["#8B4513", "#D2B48C", "#CD853F"],
  },
  {
    name: "Enchanted Forest",
    colors: ["#2E8B57", "#3CB371", "#20B2AA"],
  },
  {
    name: "Nordic Lights",
    colors: ["#C0D0E0", "#D0C0A0", "#A0A0A0"],
  },
  {
    name: "Neon Nights",
    colors: ["#FF1493", "#00FF00", "#00FFFF"],
  },
  {
    name: "Autumn Harvest",
    colors: ["#D2691E", "#8B4513", "#A0522D"],
  },
  {
    name: "Tropical Paradise",
    colors: ["#FF6347", "#32CD32", "#00CED1"],
  },
  {
    name: "Celestial Night",
    colors: ["#191970", "#483D8B", "#4B0082"],
  },
  {
    name: "Zen Garden",
    colors: ["#7BA05B", "#D3D3D3", "#8B8878"],
  },
  {
    name: "Desert Sunset",
    colors: ["#FFB347", "#E34234", "#8B4513"],
  },
  {
    name: "Soft Neutrals",
    colors: ["#C0C0C0", "#808080", "#E0E0E0"],
  },
  {
    name: "Berry Smoothie",
    colors: ["#8E4585", "#DB7093", "#FF69B4"],
  },
  {
    name: "Urban Industrial",
    colors: ["#708090", "#778899", "#B0C4DE"],
  },
  {
    name: "Sunset Glow",
    colors: ["#FF7F50", "#FF6347", "#FF4500"],
  },
  {
    name: "Emerald Forest",
    colors: ["#228B22", "#32CD32", "#006400"],
  },
  {
    name: "Coastal Calm",
    colors: ["#E0F0F0", "#A0A0A0", "#B0D0E0"],
  },
  {
    name: "Bohemian Dream",
    colors: ["#FF00FF", "#9370DB", "#BA55D3"],
  },
  {
    name: "Pastel Paradise",
    colors: ["#FFB3BA", "#BAFFC9", "#BAE1FF"],
  },
  {
    name: "Mint Chocolate",
    colors: ["#98FF98", "#3CB371", "#4B0082"],
  },
  {
    name: "Midnight Mystery",
    colors: ["#2C3E50", "#34495E", "#5D6D7E"],
  },
  {
    name: "Vintage Charm",
    colors: ["#DEB887", "#D2B48C", "#F4A460"],
  },
  {
    name: "Ocean Depths",
    colors: ["#000080", "#4169E1", "#1E90FF"],
  },
  {
    name: "Cherry Blossom",
    colors: ["#FFB7C5", "#FF69B4", "#DB7093"],
  },
  {
    name: "Moroccan Spice",
    colors: ["#CD5C5C", "#F4A460", "#D2691E"],
  },
  {
    name: "Arctic Frost",
    colors: ["#87CEEB", "#E0FFFF", "#B0E0E6"],
  },
  {
    name: "Lavender Fields",
    colors: ["#E6E6FA", "#9370DB", "#483D8B"],
  },
  {
    name: "Golden Hour",
    colors: ["#DAA520", "#FFA500", "#FF8C00"],
  },
  {
    name: "Coffee and Cream",
    colors: ["#8B4513", "#D2691E", "#FFDAB9"],
  },
  {
    name: "Urban Chic",
    colors: ["#36454F", "#626567", "#A9A9A9"],
  },
  {
    name: "Forest Retreat",
    colors: ["#A0B080", "#B0C0D0", "#C08060"],
  },
  {
    name: "Retro Pop",
    colors: ["#FF6B6B", "#4ECDC4", "#45B7D1"],
  },
  {
    name: "Sea Breeze",
    colors: ["#E0F0F0", "#A0D0E0", "#F0C090"],
  },
  {
    name: "Autumn Whisper",
    colors: ["#D2691E", "#CD853F", "#DEB887"],
  },
  {
    name: "Succulent Garden",
    colors: ["#9DC183", "#BACC81", "#86A59C"],
  },
  {
    name: "Candy Shop",
    colors: ["#FF69B4", "#FF1493", "#FF00FF"],
  },
];

export const colors: string[] = colorSchemes.map((scheme) => scheme.name);

export const materials = [
  "Silver",
  "Brass",
  "Sandstone",
  "Marble",
  "Patterned Glass",
  "Leather",
  "Wrought Iron",
  "Mahogany",
  "Maple",
  "Colored Glass",
  "Terrazzo",
  "Jacquard",
  "Textured Glass",
  "Bronze",
  "Cotton",
  "Walnut",
  "Aluminum",
  "Copper",
  "Stainless Steel",
  "Granite",
  "Slate",
  "Quartz",
  "Limestone",
  "Oak",
  "Pine",
  "Cherry",
  "Birch",
  "Clear Glass",
  "Frosted Glass",
  "Stained Glass",
  "Silk",
  "Velvet",
  "Linen",
  "Wool",
  "Concrete",
  "Ceramic",
  "Porcelain",
  "Acrylic",
  "Rattan",
  "Bamboo",
  "Cork",
  "Plywood",
  "Laminate",
  "Vinyl",
  "Tile",
];
